DROP TABLE IF EXISTS subscriptions CASCADE;
CREATE TABLE subscriptions
(
  id SERIAL PRIMARY KEY NOT NULL,
  group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);